#  This creates scripts and, as appropriate LDIF files, to be used by the
#  'LDAP user access' test to add/modify LDAP users and groups.
#
# @param base_dn
#   The LDAP Base DN
#
# @param groups
#   Hash of group name to gidNumber
#
#   * Any other required LDAP attributes required to create a posixgroup for
#     each group will be autogenerated
#
# @param users
#   Hash of user name to user info Hash
#
#   * Info Hash contains uidNumber, gidNumber, and sec_groups
#   * sec_groups is an Array of secondary group names the user belongs to
#   * Any other required LDAP attributes required to create the user will be
#     autogenerated
#
# @param ldap_server_type
#   Type of LDAP server: '389ds' or 'plain'
#
# @param test_dir
#   Base location of scripts and LDIF files generated by this class
#
# @param user_password_hash
#   The encrypted password used to set the initial password for all users
#
class site::test_ldap(
  String                      $test_dir         = '/root/test_ldap',
  String                      $base_dn          = $simp_options::ldap::base_dn,
  String                      $ldap_server_type = $simp::sssd::client::ldap_server_type,
  Hash[String,Integer]        $groups,
  Hash[String,Site::LdapUser] $users,
  String                      $user_password_hash
) {

  file { $test_dir:
    ensure  => 'directory',
    owner   => 'root',
    group   => 'root',
    mode    => '0750'
  }

  if $ldap_server_type == '389ds' {
    include 'site::test_ldap::ds389'
  }
  else {
    include 'site::test_ldap::openldap'
  }
}
