 


 -  To auto-install SIMP, type 0asimp <ENTER>07.
    - This will erase your existing system!
    - You need at least 50GB of disk space for this to succeed.
    - Add the option 0asimp_disk_crypt07 ot encrypt your disk.

 -  To auto-install SIMP with a large /var, type 0asimp-big <ENTER>07.
    - This will erase your existing system!
    - Add the option 0asimp_disk_crypt07 ot encrypt your disk.

 -  To install SIMP with disk prompt, type 0asimp-prompt<ENTER>07.
    - This will erase your existing system!

 -  To auto-install a minimized system type 0alinux-min <ENTER>07.
    - This will erase your existing system!
    - You need at least 50GB of disk space for this to succeed.
    - Add the option 0asimp_disk_crypt07 ot encrypt your disk.

 -  Use the function keys listed below for more information.

0f[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
