#  This creates OpenLDAP LDIF files and scripts to be used by the
#  'LDAP user access' test to add/modify LDAP users and groups.
#
# @param $base_dn
#   The LDAP Base DN

# @param groups
#   Hash of group name to gidNumber
#
#   * Any other required LDAP attributes required to create a posixgroup for
#     each group will be autogenerated
#
# @param users
#   Hash of user name to user info Hash
#
#   * Info Hash contains uidNumber, gidNumber, and sec_groups
#   * sec_groups is an Array of secondary group names the user belongs to
#   * Any other required LDAP attributes required to create the user will be
#     autogenerated
#
# @param $test_dir
#   Base location of scripts and LDIF files generated by this class
#
# @param $user_password_hash
#   The encrypted password used to set the initial password for all users

class site::test_ldap::openldap(
  String               $test_dir           = $site::test_ldap::test_dir,
  String               $base_dn            = $site::test_ldap::base_dn,
  Hash[String,Integer] $groups             = $site::test_ldap::groups,
  Hash[String,Hash]    $users              = $site::test_ldap::users,
  String               $user_password_hash = $site::test_ldap::user_password_hash
) {
  assert_private()

  $_ldif_dir = "${test_dir}/ldifs"
  file { $_ldif_dir:
    ensure  => 'directory',
    owner   => 'root',
    group   => 'root',
    mode    => '0750'
  }

  file { "${_ldif_dir}/add_test_users.ldif":
    owner   => 'root',
    group   => 'root',
    mode    => '0640',
    content =>  template('site/ldifs/add_test_users.ldif.erb')
  }

  file { "${_ldif_dir}/modify_test_users.ldif":
    owner   => 'root',
    group   => 'root',
    mode    => '0640',
    content =>  template('site/ldifs/modify_test_users.ldif.erb')
  }

  file { "${_ldif_dir}/force_test_users_password_reset.ldif":
    owner   => 'root',
    group   => 'root',
    mode    => '0640',
    content =>  template('site/ldifs/force_test_users_password_reset.ldif.erb')
  }

  file { "${test_dir}/add_users.sh":
    owner   => 'root',
    group   => 'root',
    mode    => '0750',
    content =>  epp('site/scripts/add_test_users_openldap.sh.epp')
  }

  file { "${test_dir}/force_password_reset.sh":
    owner   => 'root',
    group   => 'root',
    mode    => '0750',
    content =>  epp('site/scripts/force_password_reset_openldap.sh.epp')
  }
}
