# -*- ruby -*-

require "rubygems"
require "hoe"

Hoe.plugin :bundler
# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rdoc
# Hoe.plugin :version

Hoe.spec "simp-rake-helpers" do
  developer("SIMP Team", "simp@onyxpoint.net")
  license "The Apache License 2.0"
  extra_deps << ['rake', '~> 10.0']
end

# vim: syntax=ruby
