#!/usr/bin/rake -T

require 'rake/packagetask'
require 'simp/rake'

# Package Tasks
Simp::Rake::Pkg.new(File.dirname(__FILE__))

Rake::Task['pkg:tar'].clear

namespace :pkg do
  task :tar,[:chroot,:unique,:snapshot_release] => [:initialize_spec_info] do
    # Nothing to do here!
  end
end
