#!/bin/sh

umask 022

memory_free=`facter memoryfree_mb`
enough_memory=`ruby -e "$memory_free < 2200 and puts %{no}"`

if [ "$enough_memory" == 'no' ]; then
  echo "Error: You must have more than 2.2GB of RAM free to use the new Puppet Server"
  exit 1
fi

yum clean all
yum list puppetserver >& /dev/null

if [ $? -ne 0 ]; then
  echo "Error: Could not find 'puppetserver' in your yum repository."
  echo "  Please ensure that you have all the latest SIMP packages available in yum before running this script."
  exit 1
fi

rpm --quiet -q puppet-server && rpm -e --nodeps puppet-server >& /dev/null

service puppetmaster stop >& /dev/null

rm -f /etc/httpd/conf.d/puppet_passenger.conf
service httpd restart >& /dev/null

# Create the new temp directory for the puppet server
mkdir -m 0750 -p /var/lib/puppet/pserver_tmp
chown puppet:puppet /var/lib/puppet/pserver_tmp

yum -y update simp
yum -y update pupmod*

if [ $? -ne 0 ]; then
  echo "Error: Something went wrong when updating SIMP! Cannot continue."
  exit 1
fi

if [ ! -f "/etc/sysconfig/puppetserver" ]; then
  echo "Error: Something went wrong when installing the 'puppetserver' package!"
  exit 1
fi

sed -i 's|JAVA_ARGS.*|JAVA_ARGS="-Xms2g -Xmx2g -XX:MaxPermSize=256m -Djava.io.tmpdir=/var/lib/puppet/pserver_tmp"|' /etc/sysconfig/puppetserver

service puppetserver start

echo "UPGRADE COMPLETE"
echo "Please make sure the master is listening on port 8140 prior to proceeding."
echo "  This may take up to 5 minutes"
