#!/usr/bin/expect -f

set user [lindex $argv 0]
set host [lindex $argv 1]
set pass [lindex $argv 2]
set newpass [lindex $argv 3]
set extraopts [lindex $argv 4]
set timeout 10

if { $extraopts == "" } {
 spawn ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 $host -l $user ;
} else {
 spawn ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 $extraopts $host -l $user
}

# wait for password prompt
expect "*password:"
send "$pass\r"

# wait for password change prompt
expect "Current Password:"
send "$pass\r"
expect "New password:"
send "$newpass\r"
expect "Retype new password:"
send "$newpass\r"
expect "*updated successfully"

catch wait result
exit [lindex $result 3]
