#!/usr/bin/expect -f

set user [lindex $argv 0]
set host [lindex $argv 1]
set pass [lindex $argv 2]
set cmd  [lindex $argv 3]
set extraopts [lindex $argv 4]
set timeout 10

if { $extraopts == "" } {
 spawn ssh -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 $host -l $user ;
} else {
 spawn ssh -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=1 $extraopts $host -l $user
}

# wait for password prompt
expect "*password:"
send "$pass\r"

# wait for username in command line prompt before sending each command
expect "$user@$host "
send "whoami\r"
expect "$user@$host "
send "pwd\r"
expect "$user@$host "
send "$cmd\r"
expect "$user@$host "
send "exit \$?\r"

catch wait result
exit [lindex $result 3]
